config/routes.rb
Rails.application.routes.draw do
  get '/downtimes/progress', to: 'downtimes#progress'
  resources :anyparms
  resources :calevents
  resources :calibrates
  resources :dailies
  resources :downtimes
  resources :emissiondays
  resources :emissionmonths
  resources :emissions
  resources :exports
  resources :hourlies do
    collection do
      get 'progress'
    end
  end
  resources :menus
  resources :minutelies
  resources :monthlies
  resources :multiples
  resources :progresses
  resources :quarterhourlies
  resources :ranges
  resources :t1s
  resources :uptimes
  root "menus#index"
  # match "/404", to: "errors#not_found", via: :all
  # match "/500", to: "errors#internal_server_error", via: :all
end

app/controllers/menus_controller.rb
require 'pry'

class MenusController < ApplicationController

  def index

  end
  
end

app/controllers/progresses_controller.rb
class ProgressesController < ApplicationController

  # GET /progresses or /progresses.json
  def index

  end

  # GET /progresses/1 or /progresses/1.json
  def show
  end

  # GET /progresses/new
  def new
    @progress = Progress.new
  end

  # GET /progresses/1/edit
  def edit
  end

  # POST /progresses or /progresses.json
  def create
    @progress = Progress.new(progress_params)

    respond_to do |format|
      if @progress.save
        format.html { redirect_to @progress, notice: "Progress was successfully created." }
        format.json { render :show, status: :created, location: @progress }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @progress.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /progresses/1 or /progresses/1.json
  def update
    respond_to do |format|
      if @progress.update(progress_params)
        format.html { redirect_to @progress, notice: "Progress was successfully updated." }
        format.json { render :show, status: :ok, location: @progress }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @progress.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /progresses/1 or /progresses/1.json
  def destroy
    @progress.destroy
    respond_to do |format|
      format.html { redirect_to progresses_url, notice: "Progress was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_progress
      @progress = Progress.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def progress_params
      params.fetch(:progress, {})
    end
end

app/helpers/anyparms_helper.rb
module AnyparmsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calevents_helper.rb
module CaleventsHelper
end

app/helpers/calibrates_helper.rb
module CalibratesHelper
end

app/helpers/dailies_helper.rb
module DailiesHelper
end

app/helpers/downtimes_helper.rb
module DowntimesHelper
end

app/helpers/emissiondays_helper.rb
module EmissiondaysHelper
end

app/helpers/emissions_helper.rb
module EmissionsHelper
end

app/helpers/exports_helper.rb
module ExportsHelper
end

app/helpers/f1s_helper.rb
module F1sHelper
end

app/helpers/hourlies_helper.rb
module HourliesHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/minutelies_helper.rb
module MinuteliesHelper
end

app/helpers/monthlies_helper.rb
module MonthliesHelper
end

app/helpers/multiples_helper.rb
module MultiplesHelper
end

app/helpers/parms_helper.rb
module ParmsHelper
end

app/helpers/progresses_helper.rb
module ProgressesHelper
end

app/helpers/ranges_helper.rb
module RangesHelper
end

app/helpers/rollings_helper.rb
module RollingsHelper
end

app/helpers/t1s_helper.rb
module T1sHelper
end

app/views/progresses/_form.html.erb
<%= form_with(model: progress) do |form| %>
  <% if progress.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(progress.errors.count, "error") %> prohibited this progress from being saved:</h2>

      <ul>
        <% progress.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/progresses/edit.html.erb
<h1>Editing Progress</h1>

<%= render 'form', progress: @progress %>

<%= link_to 'Show', @progress %> |
<%= link_to 'Back', progresses_path %>

app/views/progresses/index.html.erb
<h1>progress</h1>

app/views/progresses/new.html.erb
<h1>New Progress</h1>

<%= render 'form', progress: @progress %>

<%= link_to 'Back', progresses_path %>

app/views/progresses/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_progress_path(@progress) %> |
<%= link_to 'Back', progresses_path %>