config/routes.rb
Rails.application.routes.draw do
  get '/downtimes/progress', to: 'downtimes#progress'
  resources :anyparms
  resources :calevents
  resources :calibrates
  resources :dailies
  resources :downtimes
  resources :emissiondays
  resources :emissionmonths
  resources :emissions
  resources :exports
  resources :hourlies do
    collection do
      get 'progress'
    end
  end
  resources :menus
  resources :minutelies
  resources :monthlies
  resources :multiples
  resources :progresses
  resources :quarterhourlies
  resources :ranges
  resources :t1s
  resources :uptimes
  root "menus#index"
  # match "/404", to: "errors#not_found", via: :all
  # match "/500", to: "errors#internal_server_error", via: :all
end

app/controllers/menus_controller.rb
require 'pry'

class MenusController < ApplicationController

  def index

  end
  
end

app/controllers/monthlies_controller.rb
class MonthliesController < ApplicationController

  def index

  end

  def show
      normalize_time_range_needed
      @columns_human = [
        # ["Monitoring","CEMS10_MonitoringCode",nil],
        ["Process","CEMS10_ProcessCode",nil],
        ["Outlet CO","CEMS10_Stack_Analyzer_CO_HDM_CM","ppm"],
        ["Outlet NO","CEMS10_Stack_Analyzer_NO_HDM_CM","ppm"],
        ["Outlet NO2","CEMS10_Stack_Analyzer_NO2_HDM_CM","ppm"],
        ["Outlet NOx","CEMS10_Stack_Analyzer_NOx_HDM_CM","ppm"],
        ["Outlet O2","CEMS10_Stack_Analyzer_O2_HDM_CM","%"],
        ["Outlet NH3","CEMS10_NH3_Analyzer_HDM_CM","ppm"],
        ["Inlet NO","CEMS10_SCR_Inlet_Analyzer_NO_HDM_CM","ppm"],
        ["Inlet NO2","CEMS10_SCR_Inlet_Analyzer_NO2_HDM_CM","ppm"],
        ["Inlet NOx","CEMS10_SCR_Inlet_Analyzer_NOx_HDM_CM","ppm"],
        ["CO Emission Rate","CEMS10_CO_Emission_Rate","lb/hr"],
        ["NOx Emission Rate","CEMS10_NOx_Emission_Rate","lb/hr"],
        ["Temperature","CEMS10_Stack_Temperature","F"],
        ["Flow","CEMS10_Stack_Flow","KSCFH"],
        ["Pressue","CEMS10_Stack_DP","KSCFH"],
      ]
      get_from_prism
  end

  private
  
end

app/helpers/anyparms_helper.rb
module AnyparmsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calevents_helper.rb
module CaleventsHelper
end

app/helpers/calibrates_helper.rb
module CalibratesHelper
end

app/helpers/dailies_helper.rb
module DailiesHelper
end

app/helpers/downtimes_helper.rb
module DowntimesHelper
end

app/helpers/emissiondays_helper.rb
module EmissiondaysHelper
end

app/helpers/emissions_helper.rb
module EmissionsHelper
end

app/helpers/exports_helper.rb
module ExportsHelper
end

app/helpers/f1s_helper.rb
module F1sHelper
end

app/helpers/hourlies_helper.rb
module HourliesHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/minutelies_helper.rb
module MinuteliesHelper
end

app/helpers/monthlies_helper.rb
module MonthliesHelper
end

app/helpers/multiples_helper.rb
module MultiplesHelper
end

app/helpers/parms_helper.rb
module ParmsHelper
end

app/helpers/progresses_helper.rb
module ProgressesHelper
end

app/helpers/ranges_helper.rb
module RangesHelper
end

app/helpers/rollings_helper.rb
module RollingsHelper
end

app/helpers/t1s_helper.rb
module T1sHelper
end

app/views/monthlies/_form.html.erb
<%= form_with(model: monthly) do |form| %>
  <% if monthly.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(monthly.errors.count, "error") %> prohibited this monthly from being saved:</h2>

      <ul>
        <% monthly.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/monthlies/edit.html.erb
<h1>Editing Monthly</h1>

<%= render 'form', monthly: @monthly %>

<%= link_to 'Show', @monthly %> |
<%= link_to 'Back', monthlies_path %>

app/views/monthlies/index.html.erb
<nav class="light-blue lighten-1" role="navigation">
    <div class="nav-wrapper container">
        <a class="brand-logo" id="logo-container" href="/"><img class="responsive-img" width="500" src="/logo-uem.svg"></a>
        <ul class="right hide-on-med-and-down">
            <li><a href="https://utilities.utexas.edu/">UEM Intranet</a></li>
        </ul>
    </div>
</nav>
<div class="section no-pad-bot" id="index-banner">
    <div class="container"><br>
        <h3 class="header center orange-text">Start, Stop, Interval</h3>
        <form action="/dailies/show" method="get">
            <div class="row"> 
                <div class="col s12">
                    <div class="row">
                        <h5>Start</h5>
                        <div class="input-field col s12">
                            <label for="autocomplete-input0">Date</label>
                            <input class="autocomplete input-field datepicker" type="text" id="autocomplete-input0" name="from" value="Oct 1, 2021">
                        </div>
                        <div class="input-field col s12">
                            <label for="autocomplete-input0t">Time</label>
                            <input type="text" class="timepicker" id="autocomplete-input0t" name="fromt" value="09:25 AM">
                        </div>
                        <h5>Stop</h5>
                        <div class="input-field col s12">
                            <label for="autocomplete-input1">Date</label>
                            <input class="autocomplete input-field datepicker" type="text" id="autocomplete-input1" name="to" value="Dec 1, 2021">
                        </div>
                        <div class="input-field col s12">
                            <label for="autocomplete-input1t">Time</label>
                            <input type="text" class="timepicker" id="autocomplete-input1t" name="tot" value="09:40 AM">
                        </div>
                        <h5>Interval (in secs)</h5>
                        <div class="input-field col s12">
                            <input class="autocomplete input-field" type="text" id="autocomplete-input2" name="interval" value="2678400">
                        </div>
                        <div class="progress">
                            <div id="progress" class="indeterminate" style="width: 0%; display:none"></div>
                        </div>
                        <div class="input-field col s12 center">
                            <input id="submit_button" class="btn-large waves-effect waves-light orange" type="submit" id="download-button" value="Go">
                        </div>
                    </div>
                </div>
            </div>
        </form>
        <br><br></div>
    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="js/materialize.js"></script>
    <script src="js/init.js"></script>
    <script src="js/range_script.js"></script>
    <script src="js/downtimes.js"></script>
</div>

app/views/monthlies/new.html.erb
<h1>New Monthly</h1>

<%= render 'form', monthly: @monthly %>

<%= link_to 'Back', monthlies_path %>

app/views/monthlies/show.html.erb
<nav class="light-blue lighten-1" role="navigation">
<div class="nav-wrapper container">
    <a class="brand-logo" id="logo-container" href="/"><img class="responsive-img" width="500" src="/logo-uem.svg"></a>
    <ul class="right hide-on-med-and-down">
        <li><a href="/report.csv">Export</a></li>
    </ul>
</div>
</nav>
<div class="section no-pad-bot" id="index-banner">
  <div class="container">
    <br>
    <h3 class="header center orange-text">Monthlies</h3>
    <h6 class="header center black-text"><%= @from_human.split(" ")[4] %></h6>
    <br>
    <p>Facility Name: University of Texas - Austin</p>
    <p>Source: Unit 10</p>
    <p>Location: Turbine #10</p>
    <table>
      <thead>
        <tr>
          <th style="text-align:center">Date</th>
          <% @columns_human.each do |column_human| %>
              <th style="text-align:center"><%= column_human[0] %></th>
          <% end %>
        </tr>
      </thead>
      <tbody>
          <% @records.each do |record| %>
            <tr>
              <td style="text-align:center"><%= record["DateTime"].strftime("%m/%d/%Y %H:%M")  %></td>
              <% @columns_human.each do |column_human| %>
                <% if column_human[1].empty? %>
                  <td style="text-align:center">(?)</td>
                <% else %>
                  <%
                    value = record[column_human[1]]
                    if value.class == Float
                      value = sprintf('%05.2f', value)
                    end
                  %>
                  <td style="text-align:center"><%= value %></td>
                <% end %>
              <% end %>
            </tr>
          <% end %>
      </tbody>
      <tfoot>
        <tr>
          <th style="text-align:center"></th>
          <th style="text-align:center"></th>
          <th style="text-align:center">Minimums: </th>
          <% @aggregate_columns.each do |aggregate_column| %>
            <th style="text-align:center">
              <%=
              if @minimums[aggregate_column].nil?
                "(none)"
              else
                sprintf('%05.2f', @minimums[aggregate_column].round(2))
              end 
              %>
            </th>
          <% end %>
        </tr>
        <tr>
          <th style="text-align:center"></th>
          <th style="text-align:center"></th>
          <th style="text-align:center">Averages: </th>
          <% @aggregate_columns.each do |aggregate_column| %>
            <th style="text-align:center"><%= sprintf('%05.2f', @averages[aggregate_column].round(2)) %></th>
          <% end %>
        </tr>
        <tr>
          <th style="text-align:center"></th>
          <th style="text-align:center"></th>
          <th style="text-align:center">Maximums: </th>
          <% @aggregate_columns.each do |aggregate_column| %>
            <th style="text-align:center">
              <%=
              if @maximums[aggregate_column].nil?
                "(none)"
              else
                sprintf('%05.2f', @maximums[aggregate_column].round(2))
              end 
              %>
            </th>
          <% end %>
        </tr>
      </tfoot>
    </table>
  </div>