config/routes.rb
Rails.application.routes.draw do
  get '/downtimes/progress', to: 'downtimes#progress'
  resources :anyparms
  resources :calevents
  resources :calibrates
  resources :dailies
  resources :downtimes
  resources :emissiondays
  resources :emissionmonths
  resources :emissions
  resources :exports
  resources :hourlies do
    collection do
      get 'progress'
    end
  end
  resources :menus
  resources :minutelies
  resources :monthlies
  resources :multiples
  resources :progresses
  resources :quarterhourlies
  resources :ranges
  resources :t1s
  resources :uptimes
  root "menus#index"
  # match "/404", to: "errors#not_found", via: :all
  # match "/500", to: "errors#internal_server_error", via: :all
end

app/controllers/exports_controller.rb
class ExportsController < ApplicationController
  
  def index
    # csv = File.open("output.csv").read
    # puts csv
    # send_data csv, :type => 'text/csv; charset=utf-8; header=present', :disposition => 'attachment; filename=output1.csv'
    # format.csv do
    #     response.headers['Content-Type'] = 'text/csv'
    #     response.headers['Content-Disposition'] = 'attachment; filename=invoice.csv'    
    #     render :template => "index.csv.erb"
    # end
    respond_to do |format|
      format.csv { render text: outxput.csv }
    end
  end

end

app/controllers/menus_controller.rb
require 'pry'

class MenusController < ApplicationController

  def index

  end
  
end

app/helpers/anyparms_helper.rb
module AnyparmsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calevents_helper.rb
module CaleventsHelper
end

app/helpers/calibrates_helper.rb
module CalibratesHelper
end

app/helpers/dailies_helper.rb
module DailiesHelper
end

app/helpers/downtimes_helper.rb
module DowntimesHelper
end

app/helpers/emissiondays_helper.rb
module EmissiondaysHelper
end

app/helpers/emissions_helper.rb
module EmissionsHelper
end

app/helpers/exports_helper.rb
module ExportsHelper
end

app/helpers/f1s_helper.rb
module F1sHelper
end

app/helpers/hourlies_helper.rb
module HourliesHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/minutelies_helper.rb
module MinuteliesHelper
end

app/helpers/monthlies_helper.rb
module MonthliesHelper
end

app/helpers/multiples_helper.rb
module MultiplesHelper
end

app/helpers/parms_helper.rb
module ParmsHelper
end

app/helpers/progresses_helper.rb
module ProgressesHelper
end

app/helpers/ranges_helper.rb
module RangesHelper
end

app/helpers/rollings_helper.rb
module RollingsHelper
end

app/helpers/t1s_helper.rb
module T1sHelper
end

app/views/exports/_form.html.erb
<%= form_with(model: export) do |form| %>
  <% if export.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(export.errors.count, "error") %> prohibited this export from being saved:</h2>

      <ul>
        <% export.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/exports/edit.html.erb
<h1>Editing Export</h1>

<%= render 'form', export: @export %>

<%= link_to 'Show', @export %> |
<%= link_to 'Back', exports_path %>

app/views/exports/index.html.erb
<h1>Exports</h1>

app/views/exports/new.html.erb
<h1>New Export</h1>

<%= render 'form', export: @export %>

<%= link_to 'Back', exports_path %>

app/views/exports/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_export_path(@export) %> |
<%= link_to 'Back', exports_path %>